name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: ', https://medium.com/@HilamGhost/affetme-mekanikleri-ve-unity-%C3%BCzerinde-kullan%C4%B1m%C4%B1-5bb833ec664a'
